### PR TITLE
tap that stop scrolling should not trigger a touchtap

### PR DESCRIPTION
**Pull request by ganmor**
The solution involve recording the scroll position at the previous touch end and comparing it with the position at the new touchstart.
Any scroll event will reset the recorded scroll position.
At touch end if the new scroll position does not match the recorded one, the tap event should not be triggered.

There might be a better way to do this but this is the only one we found so far.
It is worth noticing that this add some overhead on every tap event ( to find the parent scrolling node )

Tested on : 
Android 4.1 / 4.2 / 4.3 / 4.4 / 5.0 on Android Browser, Chrome and inside a cordova webview
Ios 7.3.2 / 8.0 => 8.4 inside and outside cordova.

Due to browserss inconsistencies it may fail on some browsers ( Won't stop the tap)
For example it does not stop the tap on iPad inside cordova in ios 8+.
The behavior mostly depends on the way the browser handle scroll event.

If the last scroll event happen at the same time as the touchstart that stop the scroll, this won't work.

### CODE REVIEW

**Comment by ganmor** [comment]
Should fix #8 on most devices

**Comment by danyan** [comment]
thanks

**Comment by superddr** [comment]
hey, why is this closed? I can still this bug when I am trying this plugin, really bothering.
iOS 10 , cordova.

**Comment by madjam002** [comment]
It is an outdated PR, and if you're using iOS 10 you can just use `WKWebView` and `onClick`, no need for this plugin anymore.

https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away

**Comment by superddr** [comment]
Thank you very much, it's good to know they have fixed this at last. I was
searching for sth. to replace onClick because on Android, buttons in a "3D
transformed iframe" some times are not responding to onClick, but touchend
is still working.
Now I have to give up the 3D transition :-<

Thanks for informing me ~

Superddr - 沈珏玮

2017-02-21 17:08 GMT+08:00 Jamie Greeff <notifications@github.com>:

**Pull request closed without merging**
